# markdownlint-cli2 configuration
# See: https://github.com/DavidAnson/markdownlint-cli2#configuration

# Glob patterns for files to lint
globs:
  - '**/*.md'

# Ignore patterns
ignores:
  - 'node_modules'
  - '.git'
  - 'CHANGELOG.md'
  - '**/node_modules/**'
  - '**/CHANGELOG.md'

# markdownlint configuration
config:
  # Disable problematic rules for technical documentation
  MD013: false # Line length (we handle this with prettier)
  MD033: false # Inline HTML (needed for badges, etc.)
  MD041: false # First line in file should be top level heading

  # Configure specific rules
  MD007: # Unordered list indentation
    indent: 2
  MD024: # Multiple headings with same content
    allow_different_nesting: true
  MD029: # Ordered list item prefix
    style: 'ordered'
