# Bun configuration for @outfitter/monorepo
# https://bun.sh/docs/runtime/configuration
# Optimized for both local development and remote agent environments

[install]
# Match pnpm's behavior for workspace packages
linkWorkspacePackages = true

# Allow semver ranges in package.json; lockfile ensures exact resolution
exact = false

# Registry configuration
registry = "https://registry.npmjs.org"

# Performance optimizations (consider security implications)
# auto = "fallback" disabled for security - prevents auto-install of unintended packages
frozenLockfile = false  # Allow lockfile updates in dev (consider true for production)
dryRun = false
production = false

[install.cache]
# Enable aggressive caching for faster installs
dir = "~/.bun/install/cache"
disable = false

[install.lockfile]
# Save lockfile for reproducible builds
save = true
print = "yarn"  # Use yarn format for better compatibility

[install.scopes]
# Optimize for our common scopes
"@outfitter" = { registry = "https://registry.npmjs.org" }
"@biomejs" = { registry = "https://registry.npmjs.org" }
"@changesets" = { registry = "https://registry.npmjs.org" }

[test]
# Default test configuration with performance optimizations
# preload path removed - file doesn't exist
coverage = true
timeout = 10000
# Parallel execution for faster tests
bail = 1  # Stop after first test failure
# Watch mode optimizations
watchExclude = ["**/node_modules/**", "**/dist/**", "**/.git/**"]

[run]
# Set NODE_ENV if not already set
env = { NODE_ENV = "development" }
# Use system shell for execution
shell = "system"
# Silent mode to reduce output noise
silent = false
# Note: bail at run-level may be ignored by Bun

# Telemetry settings (moved to top-level)
telemetry = false  # Disable telemetry for privacy

[dev]
# Enable hot reloading for development
hot = true